version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: elbandito/buildpacks
          orb-path: orb.yml
          publish-sha-version: false
          publish-branch-sha-version: true
          branch-sha-version-ref: 'dev:$CIRCLE_BRANCH'
          publish-token-variable: CIRCLE_TOKEN
          checkout: true
          requires:
            - orb-tools/lint
