version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: elbandito/buildpacks
          orb-path: orb.yml
          branch-sha-version-ref: 'dev:$CIRCLE_BRANCH'
          #orb-ref: elbandito/buildpacks@dev:${CIRCLE_BRANCH} # use this for publish
          publish-token-variable: CIRCLE_TOKEN
          checkout: true
          #validate: true # use this for publish
          requires:
            - orb-tools/lint
