version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  btd:
    jobs:
      - orb-tools/publish:
          orb-path: orb.yml
          orb-ref: elbandito/buildpacks@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true