version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: elbandito/buildpacks
          orb-path: orb.yml
          publish-sha-version: false
          publish-branch-sha-version: true
          branch-sha-version-ref: 'dev:$CIRCLE_BRANCH'
          publish-token-variable: CIRCLE_TOKEN
          checkout: true
          requires:
            - orb-tools/lint

  tag-triggered-orb-publishing:
    jobs:
      - hold-for-approval:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/
          type: approval
      - dev-promote-prod-from-git-tag:
          add-pr-comment: false
          orb-name: elbandito/buildpacks
          orb-ref: 'dev:$CIRCLE_BRANCH'
          publish-token-variable: CIRCLE_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/
          requires:
            - hold-for-approval
