version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish:
           orb-path: orb.yml
           orb-ref: elbandito/buildpacks@dev:${CIRCLE_BRANCH}
           validate: true
